#!/usr/bin/env node
// ================================================
// 📚 BOOK LOG DATA UPDATER
// ================================================
// Reads content/books/reading-log.csv and regenerates
// content/books/reading-log.js (the <script> mirror the
// bookshelf uses so stats work over file:// too).
// ================================================

const fs = require('fs');
const path = require('path');

const csvPath = path.join(__dirname, 'content', 'books', 'reading-log.csv');
const jsPath = path.join(__dirname, 'content', 'books', 'reading-log.js');

function main() {
    if (!fs.existsSync(csvPath)) {
        console.error('❌ Error: content/books/reading-log.csv not found!');
        process.exit(1);
    }

    const lines = fs.readFileSync(csvPath, 'utf-8').trim().split('\n');
    const rows = [];

    // Skip the header row (title,status,hours,page)
    for (let i = 1; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line || line.startsWith('#')) continue;

        const parts = line.split(',');
        if (parts.length < 4) continue;

        // Title may (rarely) contain commas; the last 3 fields are fixed.
        const page = parts.pop().trim();
        const hours = parts.pop().trim();
        const status = parts.pop().trim();
        const title = parts.join(',').trim();

        rows.push({
            title,
            status,
            hours: hours === '' ? 0 : parseFloat(hours),
            page: page === '' ? null : parseInt(page, 10)
        });
    }

    if (rows.length === 0) {
        console.error('❌ Error: No book rows found in reading-log.csv');
        process.exit(1);
    }

    // Line up the columns so the generated file stays readable.
    const titleWidth = Math.max(...rows.map(r => JSON.stringify(r.title).length));
    const statusWidth = Math.max(...rows.map(r => JSON.stringify(r.status).length));

    const entries = rows.map(r => {
        const title = JSON.stringify(r.title).padEnd(titleWidth);
        const status = (JSON.stringify(r.status) + ',').padEnd(statusWidth + 1);
        return `    { title: ${title}, status: ${status} hours: ${r.hours}, page: ${r.page === null ? 'null' : r.page} }`;
    }).join(',\n');

    const content = `// ================================================
// 📚 BOOKSHELF READING LOG DATA
// ================================================
// Mirror of content/books/reading-log.csv (title,status,hours,page).
// Loaded via <script> so the shelf's stats work over file:// too.
// Auto-generated by update-book.js — edit the CSV, not this file.
//   title  → must match the cover filename (without extension)
//   status → In Progress | Pause | Idle | Complete
//   hours  → total hours spent reading
//   page   → current page (null if not started / finished / untracked)
// ================================================

const BOOKSHELF_READING_LOG_DATA = [
${entries}
];
`;

    fs.writeFileSync(jsPath, content);
    console.log(`✅ Updated content/books/reading-log.js (${rows.length} books)`);
}

main();
