// ================================================
// 📚 BOOKSHELF READING LOG DATA
// ================================================
// Mirror of content/books/reading-log.csv (title,author,status,hours,page).
// Loaded via <script> so the shelf + stats work over file:// too.
// Auto-generated by update-book.js — edit the CSV, not this file.
//   title  → matches the cover filename (without extension)
//   author → shown under the title
//   file   → cover image (auto-matched from content/books/)
//   status → In Progress | Pause | Idle | Complete
//   hours  → total hours spent reading
//   page   → current page (null if not started / finished / untracked)
// ================================================

const BOOKSHELF_READING_LOG_DATA = [
    { title: "Nicomachean Ethics",                                                  author: "Aristotle",           file: "Nicomachean Ethics.jpg",                                                   status: "Pause",       hours: 0.77, page: null },
    { title: "The Philosophy of Kant",                                              author: "Immanuel Kant",       file: "The Philosophy of Kant.jpg",                                               status: "Pause",       hours: 1.48, page: 33 },
    { title: "Economic Philosophy",                                                 author: "Joan Robinson",       file: "Economic Philosophy.jpg",                                                  status: "Idle",        hours: 0, page: null },
    { title: "The Theory of Incentives",                                            author: "Laffont & Martimort", file: "The Theory of Incentives.jpg",                                             status: "Idle",        hours: 0, page: null },
    { title: "The Handbook of Experimental Economics",                              author: "Kagel & Roth",        file: "The Handbook of Experimental Economics.jpg",                               status: "Idle",        hours: 0, page: null },
    { title: "A Life of Experimental Economics - Volume II - The Next Fifty Years", author: "Vernon L. Smith",     file: "A Life of Experimental Economics - Volume II - The Next Fifty Years.webp", status: "Pause",       hours: 0.62, page: 22 },
    { title: "The Universal Book of Mathematics",                                   author: "David Darling",       file: "The Universal Book of Mathematics.jpg",                                    status: "Idle",        hours: 0, page: null },
    { title: "The Data Detective",                                                  author: "Tim Harford",         file: "The Data Detective.jpg",                                                   status: "Pause",       hours: 4.93, page: 90 },
    { title: "The Pattern Seekers",                                                 author: "Simon Baron-Cohen",   file: "The Pattern Seekers.png",                                                  status: "Idle",        hours: 0, page: null },
    { title: "Hidden Potential",                                                    author: "Adam Grant",          file: "Hidden Potential.jpg",                                                     status: "In Progress", hours: 1.25, page: 72 },
    { title: "Animal Welfare",                                                      author: "",                    file: "Animal Welfare.png",                                                       status: "Pause",       hours: 1.28, page: null },
    { title: "The Humane Economy",                                                  author: "Wayne Pacelle",       file: "The Humane Economy.jpg",                                                   status: "Pause",       hours: 3.7, page: 108 },
    { title: "Animal Farm",                                                         author: "George Orwell",       file: "Animal Farm.jpg",                                                          status: "Complete",    hours: 1.6, page: null },
    { title: "The Murder of Roger Ackroyd",                                         author: "Agatha Christie",     file: "The Murder of Roger Ackroyd.jpg",                                          status: "In Progress", hours: 4.22, page: null },
    { title: "Fifteen Dogs",                                                        author: "André Alexis",        file: "Fifteen Dogs.jpg",                                                         status: "Idle",        hours: 0, page: null },
    { title: "On Earth We're Briefly Gorgeous",                                     author: "Ocean Vuong",         file: "On Earth We're Briefly Gorgeous.jpg",                                      status: "Idle",        hours: 0, page: null },
    { title: "The Hen Who Dreamed She Could Fly",                                   author: "Sun-mi Hwang",        file: "The Hen Who Dreamed She Could Fly.jpg",                                    status: "Idle",        hours: 0, page: null }
];
