// ================================================
// 📚 BOOKSHELF READING LOG DATA
// ================================================
// Mirror of content/books/reading-log.csv (title,status,hours,page).
// Loaded via <script> so the shelf's stats work over file:// too.
// Auto-generated by update-book.js — edit the CSV, not this file.
//   title  → must match the cover filename (without extension)
//   status → In Progress | Pause | Idle | Complete
//   hours  → total hours spent reading
//   page   → current page (null if not started / finished / untracked)
// ================================================

const BOOKSHELF_READING_LOG_DATA = [
    { title: "Nicomachean Ethics"                                                 , status: "Pause",       hours: 0.77, page: null },
    { title: "The Philosophy of Kant"                                             , status: "Pause",       hours: 1.48, page: 33 },
    { title: "Economic Philosophy"                                                , status: "Idle",        hours: 0, page: null },
    { title: "The Theory of Incentives"                                           , status: "Idle",        hours: 0, page: null },
    { title: "The Handbook of Experimental Economics"                             , status: "Idle",        hours: 0, page: null },
    { title: "A Life of Experimental Economics - Volume II - The Next Fifty Years", status: "Pause",       hours: 0.62, page: 22 },
    { title: "The Universal Book of Mathematics"                                  , status: "Idle",        hours: 0, page: null },
    { title: "The Data Detective"                                                 , status: "Pause",       hours: 4.93, page: 90 },
    { title: "The Pattern Seekers"                                                , status: "Idle",        hours: 0, page: null },
    { title: "Hidden Potential"                                                   , status: "In Progress", hours: 1.25, page: 72 },
    { title: "Animal Welfare"                                                     , status: "Pause",       hours: 1.28, page: null },
    { title: "The Humane Economy"                                                 , status: "Pause",       hours: 3.7, page: 108 },
    { title: "Animal Farm"                                                        , status: "Complete",    hours: 1.6, page: null },
    { title: "The Murder of Roger Ackroyd"                                        , status: "In Progress", hours: 4.22, page: null },
    { title: "Fifteen Dogs"                                                       , status: "Idle",        hours: 0, page: null },
    { title: "On Earth We're Briefly Gorgeous"                                    , status: "Idle",        hours: 0, page: null },
    { title: "The Hen Who Dreamed She Could Fly"                                  , status: "Idle",        hours: 0, page: null }
];
